### ISSUE TITLE
experiments plugin to-dos (from FDM workshop)

### ISSUE THREAD

**Issue by alexander-haller** [uhd-urz/elAPI#40]
In GitLab by @mhxion on Jun 9, 2024, 15:22

Some to-dos from FDM workshop which I should've noted down on an issue page instead of a [PR page](https://gitlab.urz.uni-heidelberg.de/urz-elabftw/elapi/-/merge_requests/32) (which is now merged and closed).

### To-do:

- [x] Mention in CLI documenation that users willing to automate with IDs or eLab unique IDs should be mindful about the fact that the IDs aren't persistent across eLabFTW instances.
- [ ] `download-attachment`, when no explicit file path is passed with `--export`, will create a directory hierarchy `<date>/<time?>/experiment_<id>/` and export `<attachment_name>` to `experiment_<id>` directory.
- [ ] A sub-command to show list of all available attachments.
